### ISSUE TITLE
Add import package cleaning to Black

### ISSUE THREAD

**Issue by lixiliu** [dsgrid/dsgrid#105]
NOT urgent, but it would be great if Black can check (and auto-remove if possible) unused imported packages/functions/variables.

**Comment by daniel-thom** [comment]
flake8 reports unused imports. This package will do what you ask, but I'm not sure it's best: https://pypi.org/project/autoflake/. The default behavior does appear to be safe.

**Comment by elainethale** [comment]
Complete
