### ISSUE TITLE
Update doc to latest config examples

### ISSUE THREAD

**Issue by lixiliu** [dsgrid/dsgrid#142]
Update https://github.com/dsgrid/dsgrid/blob/main/docs/make_example_configs.py as necessary to show the latest configs supported by dsgrid.

For latest config examples, refer to https://github.com/dsgrid/dsgrid-project-StandardScenarios/tree/main/dsgrid_project

- Project config can now contain config for base_dimension, supplemental_dimension, and base_to_supplemental_mappings so they can be registered all at once with 
```        
Usage: dsgrid registry projects register [OPTIONS] PROJECT_CONFIG_FILE

  Register a new project with the dsgrid repository.

Options:
  -l, --log-message TEXT  reason for submission  [required]
  --help                  Show this message and exit.
```

- Dataset config can now contain dimension config so that it can be registered in one-go with 
```
Usage: dsgrid registry projects register-and-submit-dataset 
           [OPTIONS]

  Register a dataset and then submit it to a dsgrid project.

Options:
  -c, --dataset-config-file PATH  Dataset config file  [required]
  -d, --dataset-path PATH         [required]
  -m, --dimension-mapping-file PATH
                                  File containing dimension mappings to
                                  register with the dataset
  -p, --project-id TEXT           project identifier  [required]
  -l, --log-message TEXT          reason for submission  [required]
  --help                          Show this message and exit.
```
- dimension_mapping config needs to contain `mapping_type` (default is many_to_one_aggregation)

**Comment by mooneyme** [comment]
which test dataset should be used for config examples?

**Comment by elainethale** [comment]
No longer relevant
