### ISSUE TITLE
Bug w/ Annual Time _check_dataset_time_consistency_by_time_array check

### ISSUE THREAD

**Issue by mooneyme** [dsgrid/dsgrid#143]
When trying to register the EIA 861 annual data in dsgrid, I am getting this error:
`dsgrid.exceptions.DSGInvalidDataset: dataset has invalid timestamp counts, expected 2244 count for each timestamp in ['year'] but found 204 instead.`

Looks like this is happening in the `_check_dataset_time_consistency_by_time_array` function. I don't think this Is this expected behavior for the one-table format and annual time types.

This is the registration command I used

```dsgrid registry --offline datasets register "/Users/mmooney/Documents/github/github.com/dsgrid/dsgrid-project-StandardScenarios/dsgrid_project/datasets/historical/eia_861_annual_energy_use_state_sector/dataset.toml" "/Users/mmooney/OneDrive - NREL/Documents - dsgrid-load/dsgrid-v2.0/Data Coordination/eia861/processed/eia_861_annual_energy_use_state_sector/load_data.parquet" -l "test"```

You can access the data on Teams in dsgrid-load/dsgrid-v2.0 Teams channel.

This bug was identified through this SS PR: https://github.com/dsgrid/dsgrid-project-StandardScenarios/pull/51

**Comment by lixiliu** [comment]
This is not related to one_table but the fact that we now have model_year and weather_year that are not trivial.

**Comment by mooneyme** [comment]
This has been resolved as part of #144 and currently registration of the dataset works as expected.
