### ISSUE TITLE
Datasets with representative time may want to use the project's geography dimension time zone

### ISSUE THREAD

**Issue by daniel-thom** [dsgrid/dsgrid#164]
We currently require datasets with representative time to include a `time_zone` column in their geography dimension records. This may not be acceptable in all cases. Some datasets may want to use the project's time zone. We may need to a field in the dataset config to control this.

**Comment by lixiliu** [comment]
I like the idea of having a field in dataset config that says use project timezone if the user chooses to as this would be the most explicit.

But dataset can be registered without a project, what then? In the case of Tempo, doesn't that mean the dataset by itself is incomplete if its geography does not have timezone info?

**Comment by daniel-thom** [comment]
What is the use case for adding time zone information to a standalone dataset? A dataset like TEMPO without geography time zone information can still be used.

**Comment by lixiliu** [comment]
Sure, the dataset in rep time can still be loaded and used but it's not a real time series right? I just feel like timezone in this case is fundamental to Tempo's data articulation process. Without it, it's incomplete to me.

**Comment by daniel-thom** [comment]
> Sure, the dataset in rep time can still be loaded and used but it's not a real time series right? I just feel like timezone in this case is fundamental to Tempo's data articulation process. Without it, it's incomplete to me.

I think the TEMPO people have said something like, "Time zone is not relevant to our dataset. We are modeling perceived time by people." Since they are using counties for the geography dimension, I see no issue in them deferring the time zone question to the project because the project knows what time zone counties are in, or can make decisions when there is ambiguity.

**Comment by elainethale** [comment]
If the TEMPO team doesn't track county time zone, then I guess definitionally their data set is complete without that information.

However, I agree with Lixi that in another sense the data set is incomplete without that information. I think this points to the need to support the option for datasets to define time zones, but not to mandate it? (I don't think we should make the TEMPO team mark up their geography at this point, but if they did we should ingest that information.)
