### ISSUE TITLE
TEMPO mapping to odd years is adding instead of interpolating

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#181]
Annual energy in TEMPO scenarios for Taos County, NM:

![image](https://user-images.githubusercontent.com/4871688/208169955-f6bfcfe4-a32a-41fc-8723-ad6d9c192700.png)

**Comment by elainethale** [comment]
This is a good example of an automated check that would be nice to have--the choppy up-down pattern from year to year is concerning.

**Comment by elainethale** [comment]
Also, I'm not sure if this is a dsgrid issue or a data issue.

**Comment by daniel-thom** [comment]
I understand what's happening and will fix it.

**Comment by elainethale** [comment]
https://github.com/dsgrid/dsgrid/issues/180#issuecomment-1370200761 is also relevant here
