### ISSUE TITLE
Decide how to handle data_source values in projection datasets

### ISSUE THREAD

**Issue by daniel-thom** [dsgrid/dsgrid#185]
Suppose we apply the AEO growth rate dataset to ResStock. What should the resulting dataset contain in the `data_source` column? Some options from the team:
- derived
- resstock__nems_residential_module
- user-defined in query

This process could happen multiple times, and so concatenation could result in long values. Does the project know about this value ahead of time and register it? If not known ahead of time, how does the derived dataset provide the dimension records and mappings back to the project? And what would those mappings be? Would `resstock__nems_residential_module` map via duplication to both project's `resstock` and `nems_residential_module`? (that would result in massive data duplication)

If the purpose of `data_source` is to track the lineage of data, would it be better to do that with our planned dataset dependency management where the dataset config contains the information to construct and display the lineage?

Another main point to consider: if `data_source` is the discriminating field for multiple rows, it absolutely needs a unique value.

**Comment by elainethale** [comment]
I think it should just be "derived", and the derived data set metadata/Pydantic model should store the information about where the data set came from (exactly how it was derived, including the query).

**Comment by daniel-thom** [comment]
Fixed in #215
