### ISSUE TITLE
Dataset map/reduce of pivoted columns always uses sum

### ISSUE THREAD

**Issue by daniel-thom** [dsgrid/dsgrid#197]
This occurs in DatasetSchemaHandlerBase._remap_dimension_columns when it calls map_and_reduce_pivoted_dimension.
Do we need this to be configurable to use other mathematical operations?

**Comment by elainethale** [comment]
It might need to be different for different metric types? And what to do with different metric types might be more complex than an out of the box function.

**Comment by daniel-thom** [comment]
This issue is about whether we ever need to use functions like `max` or `mean` instead of just `sum` as a SQL aggregation function. What you're describing sounds like independent mapping operations.

**Comment by elainethale** [comment]
No longer relevant because work is always done in unpivoted format.
