### ISSUE TITLE
Develop conventions and infrastructure for growth rate formulas and application.

### ISSUE THREAD

**Issue by daniel-thom** [dsgrid/dsgrid#213]

**Comment by daniel-thom** [comment]
@elainethale I don't think this was completed.

**Comment by elainethale** [comment]
Set up some functions and/or enums and/or Pydantic model so it's clear how someone might add a new type of growth formula. Ideally, also add some documentation about this.

**Comment by lixiliu** [comment]
Existing name and functions are limited and not satisfactory. How to structure new growth rates / formula. Pydantic model (v2 now, different, discriminator available) with enum, match case with enum, do not allow outside code. Consider structure: flat or hierarchical.

**Comment by daniel-thom** [comment]
Fixed in #271
