### ISSUE TITLE
Need mechanism to create dimensions for derived datasets

### ISSUE THREAD

**Issue by daniel-thom** [dsgrid/dsgrid#217]
When we create the derived dataset `comstock_projected_2022` we have a problem in that the dimensions for metric, sector and subsector are unknown. (Other dimensions have already been mapped to the project and so are identical. We can attach those dimensions to the dataset.)

There are two ways to identify what the derived dataset's dimension record files should contain:
1. Look at the `required_dimensions` section of the project config for the dataset. It identifies the project base or supplemental record IDs that the dataset must contain. The derived dataset has already been through a mapping process and so these must exist. 
2. Look at the unique values in the dataset table. They should match (1) because this dataset has been through a mapping process.

In both cases we could collect these project record IDs and put them in a file and register it. This file may or may not match an existing dimension. In the case of `comstock_projected_2022` they will match the records of `comstock_reference_2022` by happenstance. 

What should we do in each of these cases?
1. The dimension records match an existing dimension in the registry. We could identify this by first searching source datasets for the derived dataset and then searching the entire registry. The dimension name and display name may or may not be appropriate for the derived dataset.
2. The dimension records do not match an existing dimension in the registry. We could generate a new one. It would be up to the user to fill in appropriate values for name and description.

There is another approach we could take to solve the problem. It is a large conceptual change but not a big change in code or config files. We could remove the need to create and register dataset dimensions.
- Projects register base and supplemental dimensions.
- Datasets have dimensions; they don't need to register them. We can find out what they are by inspecting the tables. We can record them for shortcut lookup later. But these are artifacts and not things that need to be tracked. Time may have some exceptions that need thought.
- Datasets must provide dimension mappings for any record mismatch with the project.
- When a derived dataset is registered the missing records are accounted for by the dimension-requirement section of the project config.

**Comment by elainethale** [comment]
The conclusion I got to from the Tuesday conversation:
- Derived dataset dimensions are required to either match the project base dimension or a supplemental dimension
- Thus, when creating a derived dataset:
    1. Check to see if the dimension matches the project base dimension. Use the project base dimension if it matches. If it does not, search to see if it matches a project supplemental dimension. If it matches a project supplemental dimension, use that.
    2. If it does not match a project base or supplemental dimension, generate a new dimension. The user will have to fill in appropriate values for name and description.
    3. In addition to generating the new dimension, dsgrid generates a draft update to the project config that (a) adds the new derived dataset and suggests dimension requirements, (b) adds any new supplemental dimensions
    4. The derived dataset creator reviews and edits all of the created files, then submits the derived dataset (and updated project config) to the project
