### ISSUE TITLE
Roll hours to support annual hourly (etc.) data that's for the same year, but covering a different time zone (e.g., covers UTC instead of EST)

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#274]

**Comment by ashreeta** [comment]
@lixiliu I used the code below in pyspark to manually change the column year from 2017 to 2018. I then has to convert from the string type to a timestamp.

from pyspark.sql.functions import col, when, lit, substring, concat

# Assuming your DataFrame is named df
df = df.withColumn(
    "timestamp_est",
    when(col("timestamp_est").startswith("2017"), 
         concat(lit("2018"), substring(col("timestamp_est"), 5, 16))
    ).otherwise(col("timestamp_est"))
)
