### ISSUE TITLE
Accessing TEMPO data

### ISSUE THREAD

**Issue by jfhawkin** [dsgrid/dsgrid#299]
My research group is working on a project to understand future EV charging station demand and location equity in Nebraska. We came across the report "Highly Resolved Projections of Passenger Electric Vehicle Charging Loads for the Contiguous United States" led by Arthur Yip. Looking at the issue [here](https://github.com/dsgrid/dsgrid/issues/181), it looks like we should be able to access some useful data. We're interested in county-level vehicle fleet forecasts and ideally VMT, trips, electricity consumption, or other demand estimates.

I was able to follow the instructions to get dsgrid installed and running `dsgrid --help` with the expected output. I found the [documentation](https://dsgrid.github.io/dsgrid/index.html). Looking through it, it seems like you need to a local instance of ArangoDB or access to the NREL cluster. You can then setup a query in json5 or PySpark syntax (haven't used PySpark, but syntax seems similar to Pandas). We only need a single future year, say 2030 or 2035 and the above listed data.

Could someone direct me on the process? Do I have this right (ArangoDB, then setup a query based on dsgrid documentation pages)? Is the database structure detailed somewhere to understand column names, etc. to get the right structure/keywords in a query?

Thanks!
Jason Hawkins

**Comment by daniel-thom** [comment]
Hi Jason, we actually just published several versions of the TEMPO data on AWS this week. You do not need to run the actual dsgrid software to consume the data. The link below provides guidance on how to process the data based on which table(s) you download (Pandas, DuckDB, or Spark).

[TEMPO data and instructions](https://github.com/dsgrid/dsgrid-project-StandardScenarios/blob/main/tempo_project/README.md#output-data-files-available-on-oedi)
[OEDI page](https://data.openei.org/s3_viewer?bucket=nrel-pds-dsgrid&prefix=tempo%2Ftempo-2022%2Fv1.0.0%2F) 

The OEDI page above allows you to browse the files easily, but is not good for downloading large numbers of files. You can use the AWS CLI instead. For example:

```
$ aws s3 ls s3://nrel-pds-dsgrid/tempo/tempo-2022/v1.0.0/
                           PRE annual_summary_conus/
                           PRE annual_summary_county/
                           PRE annual_summary_state/
                           PRE full_dataset/
                           PRE full_state_level/
                           PRE query_files/
                           PRE simple_profiles/
                           PRE state_level_simplified/
2024-06-12 11:24:20          0 
2024-06-12 11:32:23        114 README.txt
```
And then to download a dataset to a local directory:
```
$ mkdir annual_summary_state
$ aws s3 sync s3://nrel-pds-dsgrid/tempo/tempo-2022/v1.0.0/annual_summary_state/ annual_summary_state
```
Please reach out if you have questions.

**Comment by jfhawkin** [comment]
This is great! I think it satisfies our need.
