### ISSUE TITLE
Latest version of efs_comstock dataset not picked up by dataset_manager

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#92]
AWS shows:

![image](https://user-images.githubusercontent.com/4871688/143952399-8d1e035d-1d4c-42b4-b962-719e292108f8.png)

But when I ask dsgrid to list the datasets I get:

![image](https://user-images.githubusercontent.com/4871688/143952290-f71ac58c-f642-47a3-b6d3-d0649aae6a00.png)

I hand-synced from AWS, but I do see both versions:

![image](https://user-images.githubusercontent.com/4871688/143952568-c5927201-af3d-47a4-a2eb-49d1168a7435.png)

**Comment by mooneyme** [comment]
We are working on this at 4 PM today!
